import type { ActorEngineMatrix, InfrastructurePhase, ValueFlowStage } from "./types";

/** Unified roadmap — shipped technical phases + Codex + advanced infrastructure */
export const INFRASTRUCTURE_PHASES: InfrastructurePhase[] = [
  {
    id: "tech-0",
    group: "shipped",
    name: "Foundation",
    summary: "Arc, auth, treasury shell, Deputy tasks",
    status: "complete",
    deliverables: ["Circle Arc config", "Supabase auth", "Treasury readiness API"],
  },
  {
    id: "tech-1",
    group: "shipped",
    name: "Communities + Capital Flow",
    summary: "Programs, GitHub sensor, community install",
    status: "complete",
    deliverables: ["Community catalog", "Install flow", "Authorization ledger"],
  },
  {
    id: "tech-3",
    group: "shipped",
    name: "Multi-track sensors",
    summary: "Music, OSS, research, media, QF pipelines",
    status: "complete",
    deliverables: ["phase3-tracks", "Sensor sync cron", "OpenAlex + GitHub + music"],
  },
  {
    id: "tech-4",
    group: "shipped",
    name: "Creator claim loop",
    summary: "Claim tokens, notify policy, /claim",
    status: "complete",
    deliverables: ["HMAC claim links", "GitHub OAuth claims", "Arc memo settlement"],
  },
  {
    id: "tech-5",
    group: "shipped",
    name: "Product polish",
    summary: "Discover, Capital, Mission, command palette",
    status: "complete",
    deliverables: ["5-tab nav", "Entity pages", "Production demo 9/9"],
  },
  {
    id: "codex-1",
    group: "codex",
    name: "Proof of money",
    summary: "Value event → obligation → funding → Arc → receipt",
    status: "complete",
    deliverables: ["Live Arc treasury", "Real receipts", "No synthetic credits"],
    dependsOn: ["tech-4"],
  },
  {
    id: "codex-2",
    group: "codex",
    name: "User entry modes",
    summary: "Earn / Fund / Operate / Protect / Grow / Build / Settle dashboards",
    status: "in_progress",
    deliverables: ["Entry door routing", "Role-specific onboarding", "Dashboard deep links"],
    dependsOn: ["codex-1"],
  },
  {
    id: "codex-3",
    group: "codex",
    name: "Program templates",
    summary: "OSS fund, payroll, repayment pool, dependency insurance",
    status: "partial",
    deliverables: ["6 RFB shipped", "4 advanced templates defined", "Template deploy wiring"],
    dependsOn: ["codex-2"],
  },
  {
    id: "codex-4",
    group: "codex",
    name: "Capital modes",
    summary: "Impact, Sponsor, Repayment, Risk, Growth",
    status: "in_progress",
    deliverables: ["Capital mode types", "Repayment waterfall engine", "Fund UI mode picker"],
    dependsOn: ["codex-3"],
  },
  {
    id: "codex-5",
    group: "codex",
    name: "Network effects",
    summary: "Receipts bring every role back",
    status: "partial",
    deliverables: ["Claim receipts shipped", "Impact pages", "Weekly digests"],
    dependsOn: ["codex-2"],
  },
  {
    id: "codex-6",
    group: "codex",
    name: "Platform fees",
    summary: "Settlement %, SaaS, API, reports, repayment pool fee",
    status: "partial",
    deliverables: ["2.5% settlement bps", "Fee wallet config", "SaaS + API metering"],
    dependsOn: ["codex-4"],
  },
  {
    id: "adv-7",
    group: "advanced",
    name: "Funded founders",
    summary: "Founder grant pools, operator retainers, stranger bootstrap funding",
    status: "planned",
    deliverables: ["founder-grant-pool template", "Retainer rules on deploy", "Founder impact page"],
    dependsOn: ["codex-4"],
  },
  {
    id: "adv-8",
    group: "advanced",
    name: "DAO infrastructure",
    summary: "Proposals, votes, policy binding on ledger",
    status: "planned",
    deliverables: ["Proposal DB", "QF-weight votes", "WDL stake escrow"],
    dependsOn: ["adv-7"],
  },
  {
    id: "adv-9",
    group: "advanced",
    name: "B2B risk product",
    summary: "Company dependency fund + compliance exports",
    status: "planned",
    deliverables: ["dependency-insurance deploy", "Risk PDF export", "Procurement checkout"],
    dependsOn: ["codex-4"],
  },
  {
    id: "adv-10",
    group: "advanced",
    name: "Network flywheel",
    summary: "Cross-community Activity, portfolios, role digests",
    status: "planned",
    deliverables: ["Activity feed", "Multi-community portfolio", "Email digests per role"],
    dependsOn: ["codex-5", "adv-8"],
  },
];

export const VALUE_FLOW_STAGES: ValueFlowStage[] = [
  {
    order: 1,
    stage: "Value event",
    description: "Upstream records play, merge, citation, donation, watch",
    apiRoute: "POST /api/connectors/sensors/sync",
    onChain: false,
  },
  {
    order: 2,
    stage: "Authorization",
    description: "Connector recognizes amount owed at event time",
    apiRoute: "POST /api/authorization/ingest",
    onChain: false,
  },
  {
    order: 3,
    stage: "Funding",
    description: "Funder stake, operator deploy, or QF match pool",
    apiRoute: "POST /api/capital/fund",
    onChain: false,
  },
  {
    order: 4,
    stage: "Claimable release",
    description: "Program pool clears authorized → claimable",
    apiRoute: "POST /api/communities/deploy",
    onChain: false,
  },
  {
    order: 5,
    stage: "Settlement",
    description: "Arc USDC memo batch via Circle dev wallet",
    apiRoute: "GET /api/treasury/arc-readiness",
    onChain: true,
  },
  {
    order: 6,
    stage: "Receipt",
    description: "Public proof — tx hash, payee, program, amount",
    apiRoute: "GET /api/receipt/[id]",
    onChain: true,
  },
  {
    order: 7,
    stage: "Repayment inflow",
    description: "Future sponsorship/OC/API routed through waterfall (planned)",
    apiRoute: "POST /api/economy/repayment/simulate",
    onChain: false,
  },
];

export const ACTOR_ENGINE_MATRIX: ActorEngineMatrix[] = [
  {
    actor: "creator",
    label: "Creator",
    engines: ["earn"],
    whyTheyStay: "Money discovery + proof without changing apps",
    size: "both",
  },
  {
    actor: "funder",
    label: "Funder",
    engines: ["fund", "repayment"],
    whyTheyStay: "Choose return mode — impact or capped repayment, not charity",
    size: "both",
  },
  {
    actor: "founder",
    label: "Founder",
    engines: ["operate", "fund"],
    whyTheyStay: "Run programs; strangers fund; no spreadsheet chaos",
    size: "both",
  },
  {
    actor: "operator",
    label: "Operator",
    engines: ["operate"],
    whyTheyStay: "One install covers whole community",
    size: "large",
  },
  {
    actor: "company",
    label: "Company",
    engines: ["risk", "fund", "repayment"],
    whyTheyStay: "Fund dependencies before breakage — B2B compliance",
    size: "large",
  },
  {
    actor: "developer",
    label: "Developer",
    engines: ["build"],
    whyTheyStay: "Embed programmable flows — API + x402 revenue",
    size: "both",
  },
  {
    actor: "dao_member",
    label: "DAO member",
    engines: ["operate", "fund"],
    whyTheyStay: "Govern policy; RESOLVE executes rules",
    size: "both",
  },
  {
    actor: "audience",
    label: "Audience",
    engines: [],
    whyTheyStay: "Zero friction — upstream apps unchanged",
    size: "both",
  },
];

export function getCurrentPhaseFocus(): InfrastructurePhase[] {
  return INFRASTRUCTURE_PHASES.filter(
    (p) => p.status === "in_progress" || p.status === "planned",
  ).slice(0, 4);
}
