services:
  - type: web
    name: deputy
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma db push && npm run build
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: DEPUTY_ORACLE_PRIVATE_KEY
        sync: false
      - key: NEXT_PUBLIC_DEPUTY_ESCROW_ADDRESS
        value: "0x4e9b728a3c46315d8ec4df19b972f78b1a4f669f"
